# Kubernetes Secrets for AtlasBank

## Event Hubs Producer Secret
apiVersion: v1
kind: Secret
metadata:
  name: eventhubs-producer
  namespace: atlasbank-prod
type: Opaque
data:
  connection-string: <base64-encoded-eventhubs-connection-string>
  kafka-bootstrap-servers: <base64-encoded-kafka-bootstrap-servers>
---
# Event Hubs Consumer Secret
apiVersion: v1
kind: Secret
metadata:
  name: eventhubs-consumer
  namespace: atlasbank-prod
type: Opaque
data:
  connection-string: <base64-encoded-eventhubs-connection-string>
  kafka-bootstrap-servers: <base64-encoded-kafka-bootstrap-servers>
---
# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: atlasbank-prod
type: Opaque
data:
  connection-string: <base64-encoded-postgresql-connection-string>
  username: <base64-encoded-username>
  password: <base64-encoded-password>
---
# Redis Secret
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: atlasbank-prod
type: Opaque
data:
  connection-string: <base64-encoded-redis-connection-string>
  password: <base64-encoded-redis-password>
---
# Key Vault Secret
apiVersion: v1
kind: Secret
metadata:
  name: keyvault-secret
  namespace: atlasbank-prod
type: Opaque
data:
  url: <base64-encoded-keyvault-url>
  client-id: <base64-encoded-client-id>
  client-secret: <base64-encoded-client-secret>
---
# JWT Secret
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: atlasbank-prod
type: Opaque
data:
  secret-key: <base64-encoded-jwt-secret-key>
---
# Encryption Key Secret
apiVersion: v1
kind: Secret
metadata:
  name: encryption-secret
  namespace: atlasbank-prod
type: Opaque
data:
  encryption-key: <base64-encoded-encryption-key>
---
# External API Keys Secret
apiVersion: v1
kind: Secret
metadata:
  name: external-apis
  namespace: atlasbank-prod
type: Opaque
data:
  swift-api-key: <base64-encoded-swift-api-key>
  card-network-api-key: <base64-encoded-card-network-api-key>
  kyc-provider-api-key: <base64-encoded-kyc-provider-api-key>
  aml-provider-api-key: <base64-encoded-aml-provider-api-key>
---
# Monitoring Secret
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secret
  namespace: atlasbank-prod
type: Opaque
data:
  jaeger-endpoint: <base64-encoded-jaeger-endpoint>
  prometheus-endpoint: <base64-encoded-prometheus-endpoint>
  log-analytics-workspace-id: <base64-encoded-log-analytics-workspace-id>
