# HorizontalPodAutoscaler for Payments API (CPU based)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: paymentsapi-hpa
  namespace: atlas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: paymentsapi
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource: 
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
# HorizontalPodAutoscaler for Ledger API (CPU based)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: ledgerapi-hpa
  namespace: atlas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ledgerapi
  minReplicas: 2
  maxReplicas: 15
  metrics:
  - type: Resource
    resource: 
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 65
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
---
# HorizontalPodAutoscaler for Realtime Service (CPU based)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: realtime-hpa
  namespace: atlas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: realtime
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource: 
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
# KEDA for Settlement worker (scale on Kafka lag)
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata: 
  name: settlement-keda
  namespace: atlas
spec:
  scaleTargetRef:
    kind: Deployment
    name: settlement
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: redpanda:9092
      topic: ledger-events
      consumerGroup: settlement-consumer
      lagThreshold: "10000"
---
# KEDA for Fees worker (scale on Kafka lag)
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata: 
  name: fees-keda
  namespace: atlas
spec:
  scaleTargetRef:
    kind: Deployment
    name: fees
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: redpanda:9092
      topic: ledger-events
      consumerGroup: fees-consumer
      lagThreshold: "5000"
---
# KEDA for Recon worker (scale on Kafka lag)
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata: 
  name: recon-keda
  namespace: atlas
spec:
  scaleTargetRef:
    kind: Deployment
    name: recon
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 3
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: redpanda:9092
      topic: ledger-events
      consumerGroup: recon-consumer
      lagThreshold: "2000"
---
# VerticalPodAutoscaler for Payments API (memory optimization)
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: paymentsapi-vpa
  namespace: atlas
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: paymentsapi
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: paymentsapi
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
---
# PodDisruptionBudget for Payments API
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: paymentsapi-pdb
  namespace: atlas
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: paymentsapi
---
# PodDisruptionBudget for Ledger API
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ledgerapi-pdb
  namespace: atlas
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ledgerapi
---
# PodDisruptionBudget for Realtime Service
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: realtime-pdb
  namespace: atlas
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: realtime
