# Phase 15: Cards & Tokenization Boundary (PAN-less)
# PCI DSS Compliant Card Vault and Network Simulation

services:
  # ===== PCI ZONE (CDE) =====
  cardsvault:
    image: atlas-cards-vault:latest
    environment:
      - ASPNETCORE_URLS=http://+:5600
      - CARDS_DB=Host=atlas-postgres;Port=5432;Database=atlas_bank;Username=atlas;Password=atlas123
      - KEK_LABEL=cards-kek-1
      - NETWORK_SIM=http://networksim:5601
    depends_on: [networksim]
    ports: 
      - "5600:5600"
    networks:
      - docker_atlas-network
    # In prod: ensure this service is on a dedicated network segment with WAF/PE/mTLS
    restart: unless-stopped

  networksim:
    image: atlas-cards-networksim:latest
    environment:
      - ASPNETCORE_URLS=http://+:5601
    ports: 
      - "5601:5601"
    networks:
      - docker_atlas-network
    restart: unless-stopped

networks:
  docker_atlas-network:
    external: true
