  # Postgres perf knobs are illustrative for dev; tweak for prod via IaC
  postgres:
    image: postgres:16
    command: >
      postgres -c max_connections=300
               -c shared_buffers=1GB
               -c wal_level=replica
               -c synchronous_commit=off
               -c max_wal_size=2GB
               -c autovacuum_naptime=10s
               -c checkpoint_timeout=10min
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.9
    command: >
      redpanda start --smp 2 --memory 2G --overprovisioned --default-log-level=warn
                     --kafka-addr PLAINTEXT://0.0.0.0:9092
                     --advertise-kafka-addr PLAINTEXT://redpanda:9092
                     --set kafka_batch_max_bytes=1048576
                     --set kafka_group_initial_rebalance_delay=0

  # Auto-run ledger fast-path SQL on startup (dev)
  ledger-migrator:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    depends_on: [postgres]
    working_dir: /app
    volumes:
      - ../../:/app
    entrypoint: ["dotnet","script","-"]
    stdin_open: true
    tty: true
    # the inline script cat's the SQL and runs via psql for simplicity in dev
    command: >
      bash -lc "
        apt-get update && apt-get install -y postgresql-client &&
        psql postgresql://postgres:postgres@postgres:5432/atlas -f src/Ledger/Atlas.Ledger.Domain/sql/000_fastpath_schema.sql
      "
