global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ledger-api'
    static_configs:
      - targets: ['ledgerapi:8080']
    metrics_path: '/metrics'

  - job_name: 'payments-api'
    static_configs:
      - targets: ['paymentsapi:8080']
    metrics_path: '/metrics'

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: '/metrics'

  - job_name: 'limits'
    static_configs:
      - targets: ['limits:8080']
    metrics_path: '/metrics'

  - job_name: 'canary'
    static_configs:
      - targets: ['canary:8080']
    metrics_path: '/metrics'
