global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/atlas-slos.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "dotnet-apps"
    static_configs:
      - targets: 
        - "paymentsapi:5191"
        - "limits:5901"
        - "trust:5801"
        - "riskgraph:5401"
        - "auditapi:5551"
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    metrics_path: "/metrics"
    scrape_interval: 30s